env:
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
rules:
  no-unused-vars: 
    - warn
    - vars: all 
      args: none
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
    - allowTemplateLiterals: true
  semi:
    - error
    - never
  no-console: off
